package caddy

import (
	"fmt"
	"strings"

	"github.com/DawnKosmos/gotzer/internal/config"
)

// GenerateCaddyfile produces a Caddyfile for the platform's reverse proxy.
// Each app gets a subdomain block that proxies to its internal port.
// Caddy handles TLS automatically via Let's Encrypt.
func GenerateCaddyfile(cfg *config.PlatformConfig) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by gotzer platform\n")
	b.WriteString("# Do not edit manually — changes will be overwritten on deploy\n\n")

	for _, name := range cfg.SortedAppNames() {
		app := cfg.Apps[name]
		domain := fmt.Sprintf("%s.%s", app.Subdomain, cfg.Domain)

		b.WriteString(fmt.Sprintf("%s {\n", domain))
		b.WriteString(fmt.Sprintf("    reverse_proxy localhost:%d\n", app.Deploy.Port))
		b.WriteString("}\n\n")
	}

	return b.String()
}
