package caddy

import (
	"fmt"
	"strings"

	"github.com/DawnKosmos/gotzer/internal/config"
)

// GenerateCaddyfile produces a Caddyfile for the platform's reverse proxy.
// Each app gets a subdomain block that proxies to its internal port.
// ServiceRoutes expose Docker services (e.g. Typesense) at custom subdomains.
// Caddy handles TLS automatically via Let's Encrypt.
func GenerateCaddyfile(cfg *config.PlatformConfig) string {
	var b strings.Builder

	b.WriteString("# Auto-generated by gotzer platform\n")
	b.WriteString("# Do not edit manually — changes will be overwritten on deploy\n\n")

	// Root domain — simple status/landing block
	b.WriteString(fmt.Sprintf("%s {\n", cfg.Domain))
	b.WriteString("    respond \"OK\" 200\n")
	b.WriteString("}\n\n")

	// App subdomains
	for _, name := range cfg.SortedAppNames() {
		app := cfg.Apps[name]
		domain := fmt.Sprintf("%s.%s", app.Subdomain, cfg.Domain)

		b.WriteString(fmt.Sprintf("%s {\n", domain))
		if app.Deploy.Type == "static" {
			remotePath := app.Deploy.RemotePath
			if remotePath == "" {
				remotePath = fmt.Sprintf("/var/www/%s", name)
			}
			b.WriteString(fmt.Sprintf("    root * %s\n", remotePath))
			b.WriteString("    file_server\n")
			b.WriteString("    try_files {path} /index.html\n")
		} else {
			b.WriteString(fmt.Sprintf("    reverse_proxy localhost:%d\n", app.Deploy.Port))
		}
		b.WriteString("}\n\n")
	}

	// Docker service routes (e.g. Typesense at search.yeabuddy.de)
	for _, route := range cfg.ServiceRoutes {
		domain := fmt.Sprintf("%s.%s", route.Subdomain, cfg.Domain)
		b.WriteString(fmt.Sprintf("%s {\n", domain))
		b.WriteString(fmt.Sprintf("    reverse_proxy localhost:%d\n", route.Port))
		b.WriteString("}\n\n")
	}

	return b.String()
}
